sudo: required
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7-dev"
before_install:
  - chmod +x ./build.sh
  - chmod +x ./dev_install.sh
  - chmod +x ./post_build.sh
install:
  - ./dev_install.sh
  - ./build.sh
script:
  - ./post_build.sh
